[ios] Use square brackets syntax for nulling out toJSON property.
Closure reports an error for the old code:

../../ios/web/web_state/js/resources/common.js:40: ERROR - assignment to
property toJSON of __gCrWeb.common.JSONSafeObject.prototype
found   : null
required: function (this:Object, string=): *
  __gCrWeb.common.JSONSafeObject.prototype.toJSON = null;
  ^

BUG=None

Review-Url: https://codereview.chromium.org/2475643003
Cr-Original-Commit-Position: refs/heads/master@{#429702}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 02176404cf7da8bc6bdc4650285419d5de0e7f5a